openapi: 3.2.0
info:
  title: dotCMS REST Get Pages Content Types API
  version: '3'
  description: Returns the content types valid for a page based on the container/types on the layout
servers:
- url: /
  description: dotCMS Server
tags:
- name: getPagesContentTypes
  description: Returns the content types valid for a page based on the container/types on the layout
paths:
  /api/v1/contenttype/page:
    get:
      tags:
      - getPagesContentTypes
      summary: Retrieves a list of content types for a page
      description: Returns a list of content type objects based on the filtering criteria.
      operationId: getPagesContentTypes
      parameters:
      - name: pagePathOrId
        in: query
        description: The URL or Identifier of the page to filter content types for the palette
        schema:
          type: string
      - name: language
        in: query
        description: Optional Language id
        schema:
          type: string
          default: '-1'
      - name: filter
        in: query
        description: String to filter/search for specific content types; leave blank to return all.
        schema:
          type: string
      - name: page
        in: query
        description: 'Page number in response pagination.


          Default: `1`'
        schema:
          type: integer
          format: int64
          default: 1
      - name: per_page
        in: query
        description: 'Number of results per page for pagination.


          Default: `10`'
        schema:
          type: integer
          format: int64
          default: 10
      - name: orderby
        in: query
        description: 'Column(s) to sort the results. Multiple columns can be combined in a comma-separated list. Column names can also be set within a SQL string function, such as `upper()`.


          Some possible values:


          `name`, `velocity_var_name`, `mod_date`, `sort_order`


          `description`, `structuretype`, `category`, `inode`'
        schema:
          type: string
          default: usage
      - name: direction
        in: query
        description: 'Sort direction: choose between ascending or descending.'
        schema:
          type: string
          enum:
          - ASC
          - DESC
          default: ASC
      - name: type
        in: query
        description: List of variable names of [base content type](https://www.dotcms.com/docs/latest/base-content-types).
        style: form
        schema:
          type: array
          items:
            type: string
            enum:
            - ANY
            - CONTENT
            - WIDGET
            - FORM
            - FILEASSET
            - HTMLPAGE
            - PERSONA
            - VANITY_URL
            - KEY_VALUE
            - DOTASSET
          enum:
          - ANY
          - CONTENT
          - WIDGET
          - FORM
          - FILEASSET
          - HTMLPAGE
          - PERSONA
          - VANITY_URL
          - KEY_VALUE
          - DOTASSET
      - name: host
        in: query
        description: Filter by site identifier.
        schema:
          type: string
      responses:
        '200':
          description: Content types retrieved successfully
          content:
            application/json:
              example:
                entity:
                - baseType: string
                  clazz: string
                  defaultType: true
                  description: string
                  fixed: true
                  folder: string
                  folderPath: string
                  host: string
                  iDate: 0
                  icon: string
                  id: string
                  layout: []
                  metadata: {}
                  modDate: 0
                  multilingualable: true
                  nEntries: 0
                  name: string
                  siteName: string
                  sortOrder: 0
                  system: true
                  variable: string
                  versionable: true
                  workflows: []
                errors: []
                i18nMessagesMap: {}
                messages: []
                pagination:
                  currentPage: 0
                  perPage: 0
                  totalEntries: 0
                permissions: []
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
