openapi: 3.2.0
info:
  title: dotCMS REST Layout API
  version: '3'
servers:
- url: /
  description: dotCMS Server
tags:
- name: Layout
paths:
  /api/layout/{params}:
    get:
      operationId: getLayout
      parameters:
      - name: params
        in: path
        required: true
        schema:
          pattern: .*
          type: string
      responses:
        default:
          description: default response
          content:
            text/html: {}
      tags:
      - Layout
      summary: Get layout
      x-summary-source: derived
