openapi: 3.2.0
info:
  title: dotCMS REST System Storage API
  version: '3'
  description: Storage providers and data replication management
servers:
- url: /
  description: dotCMS Server
tags:
- name: System Storage
  description: Storage providers and data replication management
paths:
  /api/v1/storages/hello:
    get:
      tags:
      - System Storage
      operationId: hello
      responses:
        default:
          description: default response
          content:
            application/json: {}
            application/javascript: {}
      summary: Hello
      x-summary-source: derived
  /api/v1/storages/chain/_replicate/{from}/to/{to}:
    get:
      tags:
      - System Storage
      operationId: replicateStorages
      parameters:
      - name: from
        in: path
        required: true
        schema:
          type: string
          enum:
          - FILE_SYSTEM
          - DB
          - S3
          - MEMORY
          - DEFAULT_CHAIN
          - CHAIN1
          - CHAIN2
          - CHAIN3
      - name: to
        in: path
        required: true
        schema:
          type: array
          items:
            type: object
            properties:
              matrixParameters:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
              path:
                type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
            application/javascript: {}
      summary: Replicate storages
      x-summary-source: derived
